config/routes.rb
Splanet01::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }


    def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user 
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email' 
      render 'new'

    end
  end

	def destroy
        sign_out
       flash[:success] = "You have signed out" 
    redirect_to root_url
  
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	   @user = User.new
  end
   
   def show
    @user = User.find(params[:id])
  end
    
  def create
    @user = User.new(user_params)
    if @user.save
        sign_in @user 
        flash[:success] = "Welcome to the Salsa Planet!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper


  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

    def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

    def signed_in?
    !current_user.nil?
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <div class="container">
    <br>
    <hr>
      <div class="row">
        <div class="col-md-2 col-lg-3">
           <p>&copy; <a href="http://www.salsamundi.com">Salsa Mundi</a> </p>
        </div>
        <div class="col-md-2 col-lg-3">
          <%= link_to "About",   about_path %>
        </div>
        <div class="col-md-2 col-lg-3">
          <%= link_to "Contact", contact_path %>
        </div>
        <div class="col-md-2 col-lg-3">
          <a href="http://www.salsamundi.com">News</a>
        </div>
      </div>
    </div>
  </nav>  
</footer>

app/views/layouts/_header.html.erb
	<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
			<div class="navbar-brand">
			<%= link_to "salsa planet", '#' %>
			</div>       
          	<nav>
	            <ul class="nav navbar-nav">
	              <li><%= link_to "Home",   root_path %></li>
	              <li><%= link_to "Help",   help_path %></li>
	               <% if signed_in? %>
	               <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
	             
	              <% else %>
 <li><%= link_to "Sign in", signin_path %></li>
	               <% end %>
	            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_headerwithsignin.html.erb
	<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
			<div class="navbar-brand">
			<%= link_to "salsa planet", '#' %>
			</div>       
          	<nav>
	            <ul class="nav navbar-nav">
	              <li><%= link_to "Home",   root_path %></li>
	              <li><%= link_to "Help",   help_path %></li>
	               <% if signed_in? %>
	               <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
	             
	              <% else %>

 <div class="navbar-form navbar-right">
    <%= form_for(:session, url: sessions_path) do |f| %>

      <%= f.text_field :email , placeholder: 'Email'%>

      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>
 
   </div>
<li><%= link_to "Sign up", signup_path %></li>

	               <% end %>
	            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", media: "all",
		                                        "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
	 	<%= render 'layouts/header' %>
		<div class="container">
	    	<hr>
			<% flash.each do |key, value| %>
	        	<div class="alert alert-<%= key %>"><%= value %></div>
	      	<% end %>
	     	<%= yield %>
	 		<%= render 'layouts/footer' %>
	 		<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<div class="jumbotron">
<h5>About Us</h5>
<p>
  <a href="http://www.salsamundi.com">About</a>
</p>
</div>

app/views/static_pages/contact.html.erb
<div class="jumbotron">
<h5>Contact</h5>
<p>
  Contact salsamundi.com about this application
  <a href="http://www.salsamundi.com">Contact</a>
</p>
</div>

app/views/static_pages/help.html.erb
<div class="jumbotron">
<h5>Help</h5>
<p>
  Get help contact salsamundi.com about this application
  <a href="http://www.salsamundi.com">Help</a>
</p>
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h5>Welcome to the Salsa Planet Application</h5>
  <h6>
    This is the home page for the Salsa Planet Application
  </h6>
  <%= link_to "Sign up", signup_path , class: "btn btn-large btn-primary" %>
</div>

app/views/users/new.html.erb
<div class="jumbotron">
<% provide(:title, 'Sign up') %>
<h3>Sign up</h3>
<div class="row">
  <div class="col-xs-6 col-md-4">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
        <div class="col-xs-6 col-md-4 row">
          <%= f.text_field :name, placeholder: 'Name'%>
          
<br/>
<br/>
          <%= f.text_field :email, placeholder: 'Email' %>

<br/>
<br/>

          <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
       
        </div>
    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
<div class="container">
	<% provide(:title, @user.name) %>
	<div class="row">
  		<div class="col-xs-6 col-md-4">
      		<p>
        	<%= @user.name %>
        	<%= @user.email %>
      		</p>
  		</div>
	</div>
</div>
</div>